# global params
NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

# mining params
MINE_RATE = 4 * SECONDS

# wallet params
STARTING_BALANCE = 1000
